### ISSUE TITLE
Making a div overlap another div

### ISSUE THREAD

**Issue by jonatan-roytgarts** [Yonatan-Roytharts/holambier#1]
In the 'HOLAMBIER' page (get there by clicking on 'HOLAMBIER' button in the homepage) I created one div to contain the display logo, brief text and a 'read more' option. when 'read more' is clicked it displays another div with more text that covers the first div.

ISSUE: the contents of the first div overlap the second div

**Comment by rafops** [comment]
You need to make the overlaying div with absolute position and CSS property z-index greather than a certain value, for example:

``` css
#div {
  position: absolute;
  z-index: 1000;
}
```
